### ISSUE TITLE
I24 SSX: Address general purpose PVs

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx_bluesky#118]
We have a lot of general purpose PVs that are used throughout the script, many of these are actually just parameters from the EDM and so we would like to ultimately migrate them to be parameters.

## Acceptance Criteria
* For every general purpose PV in the i24 SSX scripts:
   * If they are actually parameters put them in the parameter models and only read them once
   * If not make a new issue to address them

**Comment by noemifrisina** [comment]
Some notes that may become/already are separate issues:
- `GP9` is abort button and will be addressed in #117 
- `GP104` to `GP108` are just displaying the result of the calculation for a good laser delay to set in the pump_probe screen, and not used again (Plan for this calculation kicked of by button).
- `GP11` to `GP74` are each assigned to one block of the oxford chip in the mapping lite screen. When 0 the block is not collected, when 1 the block is collected. These values are written to the `currentchip.map`` file when creating the map and the PVs are never used again in the script.
- `GP1` is the pv holding the chip type. While it's in the parameter model, a lot of the plans that read it as a one-off are actually in use before the collection - usually for alignment.
