### ISSUE TITLE
Create a generic deployment for EDM screens

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx_bluesky#32]
Following https://github.com/DiamondLightSource/mx_bluesky/pull/31 we have changed where the EDM screens are pointing for the python scripts but this will still only work for production and make it hard to test the screens in development. Instead we could do the following:
* Have a placeholder script location in the EDM e.g. `PLACEHOLDER_SCRIPT_LOC`
* Create a deploy script that will copy the EDMs to a location that's under the `.gitignore` and replace the `PLACEHOLDER_SCRIPT_LOC` with the current location

The deploy script can then be run in prod and in dev and create EDMs that point to the respective places

**Comment by noemifrisina** [comment]
This was done when testing in September
