### ISSUE TITLE
I24 ssx: Documentation

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/mx_bluesky#33]
Set up a bit of documentation as part of the wiki explaining:
 
- where it lives
- how to set visit up
- how detector is chosen
- how to run edm screens
- deployment

**Comment by noemifrisina** [comment]
See [Wiki](https://github.com/DiamondLightSource/mx_bluesky/wiki)

**Comment by dperl-dls** [comment]
this is now in the sphinx docs instead
