### ISSUE TITLE
I24 ssx: get the beam centre from file 

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/mx_bluesky#42]
When setting the fiducials (`i24ssx_moveonclick.py`), beam X/Y hardcoded and needs to be changed every time. Instead of this, we should be grabbing the values from GDA so they are current

**Comment by DominicOram** [comment]
We should use `OAVParameters` for this (https://github.com/DiamondLightSource/dodal/blob/7058d115fccc599ad36274f5bc313c9765376d74/src/dodal/devices/oav/oav_parameters.py#L19)
